name: avilatek_prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
  fonts:
    - family: MenuIcons
      fonts:
        - asset: assets/fonts/MenuIcons.ttf
