name: avilatek_prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1
  build_runner: 2.4.6
  bloc_test: ^9.1.7


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - .env
  fonts:
    - family: MenuIcons
      fonts:
        - asset: assets/fonts/MenuIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/images/app_logo_background.png"
  adaptive_icon_foreground: "assets/images/app_logo.png"



